package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"strconv"
)

func main() {
	schemaV001 := readSchema("../../../schema/lockfile-v0.0.1.json")
	schemaV002 := readSchema("../../../schema/lockfile-v0.0.2.json")
	schemaV003 := readSchema("../../../schema/lockfile-v0.0.3.json")

	var out bytes.Buffer
	fmt.Fprintln(&out, "// Code generated by go generate; DO NOT EDIT.")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "package lockfile")
	fmt.Fprintln(&out)
	fmt.Fprintf(&out, "const schemaV001 = %s\n\n", strconv.Quote(string(schemaV001)))
	fmt.Fprintf(&out, "const schemaV002 = %s\n\n", strconv.Quote(string(schemaV002)))
	fmt.Fprintf(&out, "const schemaV003 = %s\n", strconv.Quote(string(schemaV003)))

	formatted, err := format.Source(out.Bytes())
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile("schema_gen.go", formatted, 0644); err != nil {
		panic(err)
	}
}

func readSchema(path string) []byte {
	schema, err := os.ReadFile(path)
	if err != nil {
		panic(err)
	}
	return bytes.ReplaceAll(schema, []byte("\r\n"), []byte("\n"))
}
